import { generateFollowUpQuestion } from "../services/ai/followUp.service.js";

async function testFollowUp() {
  try {
    const question =
      "How would you evaluate whether your vector search is returning relevant documents?";

    const answer =
      "I would check whether the final answer generated by the LLM is correct.";

    const evaluation = {
      score: 2,

      strengths: [
        "Understands the ultimate goal of RAG"
      ],

      weaknesses: [
        "Confuses retrieval evaluation with end-to-end evaluation"
      ],

      missingConcepts: [
        "Precision@k",
        "Recall@k",
        "MRR",
        "Ground truth retrieval datasets"
      ],

      incorrectConcepts: [],

      shouldAskFollowUp: true,

      followUpReason:
        "Candidate needs to understand how to evaluate retrieval independently."
    };

    const curriculumContext = [
      {
        day: 10,
        title: "The Retrieval & Matching Engine",
        objectives: [
          "Implement semantic retrieval from the vector database",
          "Evaluate retrieval accuracy"
        ]
      }
    ];

    console.log("Generating follow-up question...\n");

    const followUp = await generateFollowUpQuestion({
      question,
      answer,
      evaluation,
      curriculumContext
    });

    console.log("FOLLOW-UP QUESTION:");
    console.log(followUp);

  } catch (error) {
    console.error("Follow-up generation failed:");
    console.error(error);
  }
}

testFollowUp();