import { analyzeCandidateAnswer } from "../services/ai/answerAnalysis.service.js";

async function testAnswerAnalysis() {
  try {
    const question =
      "How would you evaluate whether your vector search is returning relevant documents?";

    const answer =
      "I would check whether the final answer generated by the LLM is correct.";

    const curriculumContext = [
      {
        day: 10,
        title: "The Retrieval & Matching Engine",
        objectives: [
          "Implement semantic retrieval from the vector database",
          "Evaluate retrieval accuracy"
        ]
      }
    ];

    console.log("Analyzing candidate answer...\n");

    const evaluation = await analyzeCandidateAnswer({
      question,
      answer,
      curriculumContext
    });

    console.log("ANSWER EVALUATION:");
    console.log(JSON.stringify(evaluation, null, 2));

  } catch (error) {
    console.error("Answer analysis failed:");
    console.error(error);
  }
}

testAnswerAnalysis();